Added more snippets
janis-commerce/vscode-extension pull request #1
Opened 2021-02-01 19:59 UTC by Nataniel4

Added the following snippets:
- `Require a @janiscommerce package` snippet
- `Create a model` snippet
- `Create a generic API` snippet
- `Create an API Save` snippet
- `Create an API test` snippet
- `Create an API Test item` snippet

2021-02-02 14:00 UTC, jormaechea requested changes
Buenísimos @Nataniel4 !

Te dejé algunas sugerencias (algunas que no tengo ningún tipo de convicción, para que veas que te parecen).

Y acordate de agregar los snippets al README así cualquiera puede ver rápidamente que existen.

2021-02-02 14:00 UTC, jormaechea commented on snippets/snippets.json
> +			"\nmodule.exports = ${1:MyModel};\n"
```suggestion
			"\nmodule.exports = const Model = require('@janiscommerce/model');",
			"\nclass ${1:MyModel} extends Model {",
			"${3:\n\tget databaseKey() {\n\t\treturn '$4';\n\t\\}}",
			"${5:\n\tstatic get shouldCreateLogs() {\n\t\treturn false;\n\t\\}}",
			"${6:\n\tstatic get indexes() {\n\t\treturn [$7];\n\t\\}}",
			"${8:\n\tstatic get table() {\n\t\treturn '$0';\n\t\\}}",
			"};\n"
```

El getter de `uniqueIndexes` no va más.

2021-02-02 14:00 UTC, jormaechea commented on snippets/snippets.json
> +			"\nmodule.exports = ${1:MyAPI};\n"
```suggestion
			"\nmodule.exports = class ${1:MyAPI} extends API {",
			"${3:\n\tget struct() {\n\n\t\treturn struct.partial({\n\t\t\t$4\n\t\t\\});\n\t\\}}",
			"${5:\n\tasync validate() {\n\n\t\t${6:// your api validate here}\n\t\\}}",
			"\n\tasync process() {\n\n\t\t${0:// your api process here}\n\t}",
			"};\n"
```

2021-02-02 14:00 UTC, jormaechea commented on snippets/snippets.json
> +			"\nmodule.exports = ${1:MyAPI};\n"
```suggestion
			"${1:const { struct \\} = require('@janiscommerce/superstruct');}",
			"${2:\nconst mainStruct = struct.partial({\n\t$3\n\\});}",
			"\nmodule.exports = class ${4:MyAPI} extends ApiSaveData {",
			"${5:\n\tstatic get mainStruct() {\n\t\treturn mainStruct;\n\t\\}}",
			"${6:\n\tasync postStructValidate() {\n\n\t\t${7:// your validation here}\n\t\\}}",
			"${8:\n\tformat(record) {\n\n\t\t${9:return record;}\n\t\\}}",
			"${10:\n\tasync postSaveHook(id, savedItem) {\n\n\t\t${0:// your post save hook here}\n\t\\}}",
			"};\n"
```

Acá hay varias sugerencias:
1. Saque el mainStruct para afuera para que se genere una sola vez y no en cada request
2. Cambié los métodos `validate` y `process` que no son lo idea de usar por los documentados `postStructValidate` y `format`.
3. Ordené los placeholders para que queden en orden y quede más natural de arriba para abajo
4. Como en las otras, pasé el `module.exports` para adelante

Qué te parece?

2021-02-02 14:00 UTC, jormaechea commented on snippets/snippets.json
> +			"const ${1:MyAPI} = require('${2:./../../../src/api/}${3:entity}/${4:method}');",
```suggestion
			"const ${1:MyAPI} = require('${2:../../../src/api/}${3:entity}/${4:method}');",
```

Este es por TOC nomás 😅

2021-02-02 14:00 UTC, jormaechea commented on snippets/snippets.json
> +			"\tafter: (response, sandbox) => {\n\t\t${9:// your assertions here...}\n\t}",
```suggestion
			"\tbefore: sinon => {\n\t\t${8:// your stubs here...}\n\t},",
			"\tafter: (response, sinon) => {\n\t\t${9:// your assertions here...}\n\t}",
```

2021-02-02 14:00 UTC, jormaechea commented on snippets/snippets.json
> +			"\tdescription: '${1:Should do something great when the conditions are right}',",
```suggestion
			"\tdescription: 'Should ${1:do something great} when ${2:the conditions are right}',",
```

No estoy seguro de esta.. Qué te parece?

2022-07-29 03:05 UTC, Nataniel4 commented
Snippets corregidos y actualizados y un par mas agregados, solo hubo que esperar 3 dias 😛

2022-07-29 14:58 UTC, jormaechea commented
![image](https://user-images.githubusercontent.com/5612500/181787555-8e63104f-7f1a-47fd-b4ca-f3d80ff94220.png)

2022-07-29 15:16 UTC, jormaechea approved these changes

2022-07-29 15:22 UTC, jormaechea commented on README.md
> +
@Nataniel4 Falto el de require de packages de `@janiscommerce` !

2022-07-29 15:23 UTC, gastonpereyra commented on README.md
> +- [Model](https://www.npmjs.com/package/@janiscommerce/model)
No estaría copado explicar un poco más, aunque sea con un ejemplo que hace exactamente cada snippet ?, que datos te ayuda a completar por ejemplo.

2022-07-29 15:24 UTC, jormaechea commented on README.md
> +- [Model](https://www.npmjs.com/package/@janiscommerce/model)
Si metemos un GIF del snippet en uso me vuelvo locooo 🤯

2022-07-29 15:28 UTC, gastonpereyra reviewed
Es posible incluir:
* Event-Listener y Event Emitter ?
* Para los YAML de los eventos ? (tanto el schema como para subscribirse a un evento)
* Microservicall (safeCall y safeList) ?
* Cuando definis los steps de una Step-Functions ?

2022-07-29 15:28 UTC, gastonpereyra commented on README.md
> +- [Model](https://www.npmjs.com/package/@janiscommerce/model)
UUUUUHH Seria tremendo

2022-07-29 16:34 UTC, Nataniel4 commented on README.md
> +- [Model](https://www.npmjs.com/package/@janiscommerce/model)
😎

2022-07-29 16:35 UTC, Nataniel4 commented
> Es posible incluir:
> 
> * Event-Listener y Event Emitter ?
> * Para los YAML de los eventos ? (tanto el schema como para subscribirse a un evento)
> * Microservicall (safeCall y safeList) ?
> * Cuando definis los steps de una Step-Functions ?

Si pero en otro PR 😭

2022-08-02 15:50 UTC, jormaechea approved these changes

2022-08-02 15:50 UTC, merged